# Generated by Django 2.2.1 on 2019-05-11 08:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('status', models.IntegerField(choices=[(0, '删除'), (1, '正常')], verbose_name='评论状态')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('updated', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='回复内容')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='回复时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='comments.Comment', verbose_name='评论回复')),
            ],
            options={
                'verbose_name': '回复评论',
                'verbose_name_plural': '回复评论',
            },
        ),
    ]
