# Generated by Django 2.2.1 on 2019-05-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='头像'),
        ),
    ]
